// Package projinit calibrates the agreement to a single repository: it
// detects the project's stack and writes a project-local .claude/ with only
// the antipattern checks that matter for that language, instead of the
// monolithic multi-language global rules.
package projinit

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Stack struct {
	ID     string // go, node, python, rust
	Name   string
	marker string // file whose presence identifies the stack
	checks string // claudiao-check blocks for this stack
}

var stacks = []Stack{
	{ID: "go", Name: "Go", marker: "go.mod", checks: goChecks},
	{ID: "node", Name: "TypeScript/JavaScript", marker: "package.json", checks: nodeChecks},
	{ID: "python", Name: "Python", marker: "pyproject.toml", checks: pythonChecks},
	{ID: "python", Name: "Python", marker: "requirements.txt", checks: pythonChecks},
	{ID: "rust", Name: "Rust", marker: "Cargo.toml", checks: rustChecks},
}

// Detect returns the stacks present in dir (deduped by ID, stable order).
func Detect(dir string) []Stack {
	seen := map[string]bool{}
	var out []Stack
	for _, s := range stacks {
		if seen[s.ID] {
			continue
		}
		if _, err := os.Stat(filepath.Join(dir, s.marker)); err == nil {
			seen[s.ID] = true
			out = append(out, s)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

type Result struct {
	Stacks  []string
	Written []string
	Skipped []string
}

// Generate writes a project-local .claude/rules/<stack>-checks.md per detected
// stack plus a minimal CLAUDE.md. Existing files are skipped unless force is
// set, so re-running never clobbers local edits.
func Generate(dir string, force bool) (Result, error) {
	found := Detect(dir)
	if len(found) == 0 {
		return Result{}, fmt.Errorf("no known stack detected in %s (looked for go.mod, package.json, pyproject.toml, requirements.txt, Cargo.toml)", dir)
	}

	// Refuse to write through a symlinked .claude or .claude/rules — a
	// "project-local" init that silently lands files outside the repo is
	// surprising at best.
	claudeDir := filepath.Join(dir, ".claude")
	rulesDir := filepath.Join(claudeDir, "rules")
	for _, p := range []string{claudeDir, rulesDir} {
		if info, err := os.Lstat(p); err == nil && info.Mode()&os.ModeSymlink != 0 {
			return Result{}, fmt.Errorf("%s is a symlink; refusing to write through it", p)
		}
	}
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return Result{}, err
	}

	var res Result
	for _, s := range found {
		res.Stacks = append(res.Stacks, s.ID)
		target := filepath.Join(rulesDir, s.ID+"-checks.md")
		wrote, err := writeIfAbsent(target, stackDoc(s), force)
		if err != nil {
			return res, err
		}
		if wrote {
			res.Written = append(res.Written, target)
		} else {
			res.Skipped = append(res.Skipped, target)
		}
	}

	claudeMD := filepath.Join(dir, ".claude", "CLAUDE.md")
	wrote, err := writeIfAbsent(claudeMD, projectClaudeMD(found), force)
	if err != nil {
		return res, err
	}
	if wrote {
		res.Written = append(res.Written, claudeMD)
	} else {
		res.Skipped = append(res.Skipped, claudeMD)
	}
	return res, nil
}

func writeIfAbsent(path, content string, force bool) (bool, error) {
	if !force {
		if _, err := os.Stat(path); err == nil {
			return false, nil
		}
	}
	// CreateTemp (O_EXCL + random name) avoids the predictable-temp-name
	// symlink-follow vector that a fixed ".tmp" suffix has.
	f, err := os.CreateTemp(filepath.Dir(path), ".claudiao-*.tmp")
	if err != nil {
		return false, err
	}
	tmp := f.Name()
	if _, err := f.WriteString(content); err != nil {
		f.Close()
		os.Remove(tmp)
		return false, err
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp)
		return false, err
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return false, err
	}
	return true, nil
}

func stackDoc(s Stack) string {
	return fmt.Sprintf("# Rules — %s checks (project-local, generated by `claudiao init`)\n\n"+
		"High-precision antipatterns for this stack, executed by `claudiao check`\n"+
		"against the added lines of the diff. Edit freely — `claudiao init` will\n"+
		"not overwrite this file unless you pass `--force`.\n\n%s", s.Name, s.checks)
}

func projectClaudeMD(found []Stack) string {
	var names []string
	for _, s := range found {
		names = append(names, s.Name)
	}
	return fmt.Sprintf("# Project agreement (claudiao init)\n\n"+
		"Detected stack: **%s**.\n\n"+
		"This project inherits the global working agreement in `~/.claude/CLAUDE.md`.\n"+
		"The `.claude/rules/*-checks.md` files here add stack-specific antipattern\n"+
		"checks; run them with:\n\n"+
		"```\nclaudiao check\n```\n\n"+
		"`claudiao check` loads both the global rules and this project's\n"+
		"`.claude/rules` automatically.\n", strings.Join(names, ", "))
}

// go-discarded-error catches an error-named value assigned to _
// (`_ = err`, `_ = readErr`). Scope is deliberately narrow: a line regex
// cannot tell which tuple position holds the error, so positional discards
// (`foo, _ := bar()`) are out of scope. Minor, so it never blocks a commit —
// it is a smell flag, not a gate.
const goChecks = "```claudiao-check\n" +
	"id: go-discarded-error\n" +
	"severity: minor\n" +
	"files: *.go\n" +
	"pattern: _\\s*=\\s*\\w*[eE]rr\\b\n" +
	"```\n\n" +
	"```claudiao-check\n" +
	"id: go-panic-in-lib\n" +
	"severity: minor\n" +
	"files: *.go\n" +
	"pattern: \\bpanic\\(\n" +
	"```\n\n" +
	"```claudiao-check\n" +
	"id: go-empty-interface\n" +
	"severity: minor\n" +
	"files: *.go\n" +
	"pattern: \\binterface\\{\\}\n" +
	"```\n"

const nodeChecks = "```claudiao-check\n" +
	"id: ts-explicit-any\n" +
	"severity: major\n" +
	"files: *.ts\n" +
	"pattern: :\\s*any\\b\n" +
	"```\n\n" +
	"```claudiao-check\n" +
	"id: ts-ts-ignore\n" +
	"severity: major\n" +
	"files: *.ts\n" +
	"pattern: @ts-ignore\n" +
	"```\n\n" +
	"```claudiao-check\n" +
	"id: js-console-log\n" +
	"severity: minor\n" +
	"pattern: \\bconsole\\.(log|debug)\\(\n" +
	"```\n"

// py-bare-except matches only `except:` with no exception type (the
// swallow-everything antipattern), not `except ValueError:`. A line regex
// cannot see the `pass` on the next line, so the check does not promise it.
const pythonChecks = "```claudiao-check\n" +
	"id: py-bare-except\n" +
	"severity: major\n" +
	"files: *.py\n" +
	"pattern: ^\\s*except\\s*:\\s*$\n" +
	"```\n\n" +
	"```claudiao-check\n" +
	"id: py-print-debug\n" +
	"severity: minor\n" +
	"files: *.py\n" +
	"pattern: ^\\s*print\\(\n" +
	"```\n"

const rustChecks = "```claudiao-check\n" +
	"id: rust-unwrap\n" +
	"severity: minor\n" +
	"files: *.rs\n" +
	"pattern: \\.unwrap\\(\\)\n" +
	"```\n\n" +
	"```claudiao-check\n" +
	"id: rust-unsafe\n" +
	"severity: major\n" +
	"files: *.rs\n" +
	"pattern: \\bunsafe\\b\n" +
	"```\n"
