package immune

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Ledger is the repo's case law: the durable record of every antibody, kept
// under .claude/immune/ so it is versioned with the project and read by the
// binary (never by the model — zero context cost).
type Ledger struct {
	Antibodies map[string]Antibody `json:"antibodies"` // keyed by Antibody.ID
}

func dir(repoRoot string) string { return filepath.Join(repoRoot, ".claude", "immune") }
func ledgerPath(r string) string { return filepath.Join(dir(r), "ledger.json") }
func checksPath(r string) string { return filepath.Join(r, ".claude", "rules", "immune-checks.md") }

// Load reads the ledger, returning an empty one when none exists yet.
func Load(repoRoot string) (*Ledger, error) {
	data, err := os.ReadFile(ledgerPath(repoRoot))
	if err != nil {
		if os.IsNotExist(err) {
			return &Ledger{Antibodies: map[string]Antibody{}}, nil
		}
		return nil, err
	}
	var l Ledger
	if err := json.Unmarshal(data, &l); err != nil {
		return nil, fmt.Errorf("corrupt immune ledger: %w", err)
	}
	if l.Antibodies == nil {
		l.Antibodies = map[string]Antibody{}
	}
	return &l, nil
}

// Add inserts or refreshes antibodies, reporting which ones are new. An
// existing antibody is updated in place (hit counts grow over time) without
// losing its identity.
func (l *Ledger) Add(abs []Antibody) (added []Antibody) {
	for _, a := range abs {
		if _, ok := l.Antibodies[a.ID]; !ok {
			added = append(added, a)
		}
		l.Antibodies[a.ID] = a
	}
	return added
}

// Save writes the ledger and re-renders the executable checks file atomically.
func (l *Ledger) Save(repoRoot string) error {
	// Refuse symlinked targets BEFORE any MkdirAll, which would otherwise
	// follow the link and create directories outside the repo.
	for _, p := range []string{
		filepath.Join(repoRoot, ".claude"),
		filepath.Join(repoRoot, ".claude", "immune"),
		filepath.Join(repoRoot, ".claude", "rules"),
	} {
		if err := refuseSymlink(p); err != nil {
			return err
		}
	}
	if err := os.MkdirAll(dir(repoRoot), 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(l, "", "  ")
	if err != nil {
		return err
	}
	if err := writeAtomic(ledgerPath(repoRoot), data); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(repoRoot, ".claude", "rules"), 0o755); err != nil {
		return err
	}
	return writeAtomic(checksPath(repoRoot), []byte(l.renderChecks()))
}

// renderChecks materializes the antibodies as a claudiao-check markdown file
// that `claudiao check` already loads from the project-local .claude/rules.
func (l *Ledger) renderChecks() string {
	var b strings.Builder
	b.WriteString("# Immune checks (generated by `claudiao immune` — do not hand-edit)\n\n")
	b.WriteString("Each block is an antibody: an antipattern this repo already fixed at\n")
	b.WriteString("least once. Regenerate with `claudiao immune scan`.\n\n")
	for _, a := range l.sorted() {
		// A pattern that does not compile (e.g. a hand-edited ledger) must not
		// be rendered: claudiao check aborts its whole load on one bad regex,
		// which would silently disable every check. Skip it here.
		if _, err := regexp.Compile(a.Pattern); err != nil {
			continue
		}
		fmt.Fprintf(&b, "<!-- scar: removed in %d fix commit(s); sample: %s -->\n",
			a.Scar.Hits, oneLine(a.Scar.Sample))
		b.WriteString("```claudiao-check\n")
		fmt.Fprintf(&b, "id: %s\n", a.ID)
		fmt.Fprintf(&b, "severity: %s\n", a.Severity)
		fmt.Fprintf(&b, "pattern: %s\n", a.Pattern)
		b.WriteString("```\n\n")
	}
	return b.String()
}

func (l *Ledger) sorted() []Antibody {
	var out []Antibody
	for _, a := range l.Antibodies {
		out = append(out, a)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Scar.Hits != out[j].Scar.Hits {
			return out[i].Scar.Hits > out[j].Scar.Hits
		}
		return out[i].ID < out[j].ID
	})
	return out
}

func oneLine(s string) string {
	s = strings.ReplaceAll(strings.ReplaceAll(s, "\n", " "), "-->", "--")
	if len(s) > 100 {
		s = s[:100] + "…"
	}
	return s
}

func refuseSymlink(p string) error {
	if info, err := os.Lstat(p); err == nil && info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%s is a symlink; refusing to write through it", p)
	}
	return nil
}

func writeAtomic(path string, data []byte) error {
	f, err := os.CreateTemp(filepath.Dir(path), ".immune-*.tmp")
	if err != nil {
		return err
	}
	tmp := f.Name()
	if _, err := f.Write(data); err != nil {
		f.Close()
		os.Remove(tmp)
		return err
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return err
	}
	return nil
}
